steps:
  # Install
  - name: "gcr.io/$PROJECT_ID/npm:latest"
    args: ["install"]
  # Build
  - name: "gcr.io/$PROJECT_ID/npm:latest"
    args: ["run", "build"]
  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "-P", "default"]
