steps:
  # Install
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  # Build
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build"]
  # Deploy
  - name: "gcr.io/$PROJECT_ID/firebase"
    args: ["deploy", "-P", "default"]
